name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALGORITHM: ${{ secrets.ALGORITHM }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copia os arquivos
      uses: actions/checkout@v4

    - name: Instala o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instala o Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Instala as dependencias do projeto
      run: poetry install

    - name: Executa os testes
      run: poetry run pytest